Repository pyMBE-dev/pyMBE, pull requests merged in 2024-05, with the labels that each got.

#55 Add Pylint
  .github/workflows/testsuite.yml
  .pylintrc
  Makefile
  lib/analysis.py
  lib/create_cg_from_pdb.py
  lib/handy_functions.py
  maintainer/configure_venv.py
  maintainer/standarize_data.py
  pyMBE.py
  samples/Beyer2024/README.md
  samples/Beyer2024/create_paper_data.py
  samples/Beyer2024/globular_protein.py
  samples/Beyer2024/peptide.py
  samples/Beyer2024/weak_polyelectrolyte_dialysis.py
  samples/branched_polyampholyte.py
  samples/peptide.py
  samples/peptide_mixture_grxmc_ideal.py
  samples/plot_HH.py
  samples/salt_solution_gcmc.py
  testsuite/bond_tests.py
  testsuite/cph_ideal_tests.py
  testsuite/create_molecule_position_test.py
  testsuite/gcmc_tests.py
  testsuite/generate_perpendicular_vectors_test.py
  testsuite/globular_protein_tests.py
  testsuite/grxmc_ideal_tests.py
  testsuite/henderson_hasselbalch_tests.py
  testsuite/lj_tests.py
  testsuite/parameter_test.py
  testsuite/peptide_tests.py
  testsuite/read-write-df_test.py
  testsuite/seed_test.py
  testsuite/set_particle_acidity_test.py
  testsuite/weak_polyelectrolyte_dialysis_test.py
  tutorials/pyMBE_tutorial.ipynb
  tutorials/solution_tutorial.ipynb
  visualization/create_vmd_script.py
  visualization/vmd-traj.py
Labels: ci-improvement, code quality

#57 Add Codecov
  .codecov.yml
  .github/actions/dependencies/action.yml
  .github/workflows/samples.yml
  .github/workflows/testsuite.yml
  Makefile
  README.md
  lib/analysis.py
  pyMBE.py
  testsuite/serialization_test.py
Labels: ci-improvement

#65 add admin team to authors list
  AUTHORS.md
Labels: documentation
