Repository pyMBE-dev/pyMBE, pull requests merged in 2024-11, with the labels that each got.

#95 refactor sample scripts
  CHANGELOG.md
  README.md
  lib/analysis.py
  samples/Beyer2024/README.md
  samples/README.md
  samples/analyze_time_series.py
  samples/branched_polyampholyte.py
  samples/peptide.py
  samples/peptide_cpH.py
  samples/peptide_mixture_grxmc_ideal.py
  samples/plot_HH.py
  samples/plot_branched_polyampholyte.py
  samples/plot_peptide_cpH.py
  samples/plot_peptide_mixture_grxmc_ideal.py
  samples/salt_solution_gcmc.py
  testsuite/CTestTestfile.cmake
  testsuite/analysis_tests.py
  testsuite/cph_ideal_tests.py
  testsuite/grxmc_ideal_tests.py
Labels: bug, documentation, ci-improvement, code quality

#93 General lattice builder
  lib/lattice.py
  testsuite/CTestTestfile.cmake
  testsuite/lattice_builder.py
  tutorials/lattice_builder.ipynb
Labels: enhancement

#101 Add unit tests for globular proteins features
  CHANGELOG.md
  pyMBE.py
  samples/Beyer2024/globular_protein.py
  testsuite/CTestTestfile.cmake
  testsuite/globular_protein_functional_tests.py
  testsuite/globular_protein_unit_tests.py
  testsuite/tests_data/protein_topology_dict.json
Labels: bug, ci-improvement

#99 include backbone vector in create_molecule
  AUTHORS.md
  CHANGELOG.md
  pyMBE.py
  testsuite/define_and_create_molecules_unit_tests.py
Labels: enhancement

#105 fix output for trajectory files for globular proteins for CI testing
  samples/Beyer2024/globular_protein.py
  testsuite/globular_protein_functional_tests.py
Labels: bug

#104 Add code of conduct of the pyMBE community
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: community
