Repository pyMBE-dev/pyMBE, pull requests merged in 2024-06, with the labels that each got.

#63 Fix wrong setup of LJ, improve CI and coverage
  Makefile
  lib/create_cg_from_pdb.py
  pyMBE.py
  samples/Beyer2024/create_paper_data.py
  samples/Beyer2024/globular_protein.py
  samples/Beyer2024/peptide.py
  samples/Beyer2024/weak_polyelectrolyte_dialysis.py
  samples/peptide_mixture_grxmc_ideal.py
  testsuite/calculate_net_charge_unit_test.py
  testsuite/create_molecule_position_test.py
  testsuite/define_and_create_molecules_unit_tests.py
  testsuite/globular_protein_tests.py
  testsuite/globular_protein_unit_tests.py
  testsuite/parameter_test.py
  testsuite/peptide_tests.py
  testsuite/read-write-df_test.py
  testsuite/setup_salt_ions_unit_tests.py
  testsuite/test_parameters/test_FENE.json
  testsuite/test_parameters/test_molecules.json
  testsuite/test_parameters/test_non_valid_bond.json
  testsuite/test_parameters/test_non_valid_object.json
Labels: bug, ci-improvement, code quality

#68 Copyright
  Makefile
  lib/analysis.py
  lib/create_cg_from_pdb.py
  lib/handy_functions.py
  maintainer/configure_venv.py
  maintainer/header_template_license.txt
  maintainer/standarize_data.py
  pyMBE.py
  samples/Beyer2024/create_paper_data.py
  samples/Beyer2024/globular_protein.py
  samples/Beyer2024/peptide.py
  samples/Beyer2024/weak_polyelectrolyte_dialysis.py
  samples/branched_polyampholyte.py
  samples/peptide.py
  samples/peptide_mixture_grxmc_ideal.py
  samples/plot_HH.py
  samples/salt_solution_gcmc.py
  testsuite/bond_tests.py
  testsuite/calculate_net_charge_unit_test.py
  testsuite/cph_ideal_tests.py
  testsuite/create_molecule_position_test.py
  testsuite/define_and_create_molecules_unit_tests.py
  testsuite/gcmc_tests.py
  testsuite/generate_perpendicular_vectors_test.py
  testsuite/globular_protein_tests.py
  testsuite/globular_protein_unit_tests.py
  testsuite/grxmc_ideal_tests.py
  testsuite/henderson_hasselbalch_tests.py
  testsuite/lj_tests.py
  testsuite/parameter_test.py
  testsuite/peptide_tests.py
  testsuite/read-write-df_test.py
  testsuite/seed_test.py
  testsuite/serialization_test.py
  testsuite/set_particle_acidity_test.py
  testsuite/setup_salt_ions_unit_tests.py
  testsuite/weak_polyelectrolyte_dialysis_test.py
  tutorials/pyMBE_tutorial.ipynb
  tutorials/solution_tutorial.ipynb
  visualization/create_vmd_script.py
  visualization/vmd-traj.py
Labels: documentation, good first issue

#62 analysis tests
  Makefile
  lib/analysis.py
  pyMBE.py
  samples/Beyer2024/globular_protein.py
  testsuite/analysis_tests.py
  testsuite/gcmc_tests.py
  testsuite/globular_protein_tests.py
  testsuite/serialization_test.py
  testsuite/tests_data/N-064_Solvent-good_Init-coil_time_series.csv
  testsuite/tests_data/N-064_Solvent-good_Init-coil_time_series_analyzed.csv
  testsuite/tests_data/N-128_Dens-0.2_eps-0.71_Init-coil_time_series.csv
  testsuite/tests_data/average_data.csv
  testsuite/weak_polyelectrolyte_dialysis_test.py
Labels: ci-improvement

#70 replace print_reduced_units by get_reduced_units
  pyMBE.py
  testsuite/serialization_test.py
  tutorials/pyMBE_tutorial.ipynb
Labels: code quality

#72 Various small changes
  Makefile
  maintainer/standarize_data.py
  parameters/peptides/Blanco2021.json
  parameters/peptides/Lunkad2021.json
  pyMBE.py
  samples/Beyer2024/create_paper_data.py
  samples/Beyer2024/globular_protein.py
  samples/Beyer2024/peptide.py
  samples/Beyer2024/weak_polyelectrolyte_dialysis.py
  samples/branched_polyampholyte.py
  samples/peptide.py
  samples/peptide_mixture_grxmc_ideal.py
  samples/plot_HH.py
  samples/salt_solution_gcmc.py
  testsuite/bond_tests.py
  testsuite/calculate_net_charge_unit_test.py
  testsuite/charge_number_map_tests.py
  testsuite/cph_ideal_tests.py
  testsuite/create_molecule_position_test.py
  testsuite/define_and_create_molecules_unit_tests.py
  testsuite/gcmc_tests.py
  testsuite/generate_coordinates_tests.py
  testsuite/generate_perpendicular_vectors_test.py
  testsuite/globular_protein_tests.py
  testsuite/globular_protein_unit_tests.py
  testsuite/grxmc_ideal_tests.py
  testsuite/henderson_hasselbalch_tests.py
  testsuite/lj_tests.py
  testsuite/parameter_test.py
  testsuite/peptide_tests.py
  testsuite/read-write-df_test.py
  testsuite/seed_test.py
  testsuite/serialization_test.py
  testsuite/set_particle_acidity_test.py
  testsuite/setup_salt_ions_unit_tests.py
  testsuite/weak_polyelectrolyte_dialysis_test.py
  tutorials/pyMBE_tutorial.ipynb
  tutorials/solution_tutorial.ipynb
Labels: code quality
