Repository pyMBE-dev/pyMBE, pull requests merged in 2024-04, with the labels that each got.

#26 Fixing perpendicular vector
  AUTHORS.md
  Makefile
  pyMBE.py
  samples/peptide.py
  testsuite/generate_perpendicular_vectors_test.py
Labels: bug, ci-improvement

#22 21 make calculate hh donnan independent of espresso
  Makefile
  pyMBE.py
  samples/Beyer2024/create_paper_data.py
  samples/Beyer2024/run_test_protein.py
  samples/branched_polyampholyte.py
  samples/peptide.py
  samples/peptide_mixture_grxmc_ideal.py
  samples/peptide_mixture_grxmc_unified_ideal.py
  samples/plot_HH.py
  testsuite/henderson_hasselbalch_tests.py
  testsuite/henderson_hasselbalch_tests_data/HH.csv
  testsuite/henderson_hasselbalch_tests_data/HH_Donnan.csv
Labels: ci-improvement, code quality

#30 Improve read and write functions
  Makefile
  pyMBE.py
  samples/Beyer2024/globular_protein.py
  samples/branched_polyampholyte.py
  samples/peptide.py
  samples/peptide_mixture_grxmc_ideal.py
  testsuite/lj_tests.py
  testsuite/read-write-df_test.py
  tutorials/solution_tutorial.ipynb
Labels: ci-improvement, code quality

#33 Add test of G-RxMC (ideal).
  Makefile
  pyMBE.py
  samples/branched_polyampholyte.py
  samples/peptide.py
  samples/peptide_mixture_grxmc_ideal.py
  testsuite/cph_ideal_tests.py
  testsuite/grxmc_ideal_tests.py
  testsuite/lj_tests.py
Labels: ci-improvement

#34 Fix initial pos mol
  Makefile
  pyMBE.py
  testsuite/create_molecule_position_test.py
Labels: bug

#24 added value error if pka not provided for acidic or basic particles
  Makefile
  parameters/peptides/Avogadro_parametrization.txt
  parameters/peptides/Blanco2020.txt
  parameters/peptides/Lunkad2021.txt
  pyMBE.py
  testsuite/set_particle_acidity_test.py
Labels: bug, ci-improvement

#41 Bonds
  Makefile
  README.md
  parameters/peptides/Avogadro_parametrization.txt
  parameters/peptides/Blanco2020.txt
  parameters/peptides/Lunkad2021.txt
  pyMBE.py
  samples/Beyer2024/weak_polyelectrolyte_dialysis.py
  samples/branched_polyampholyte.py
  samples/peptide.py
  samples/peptide_mixture_grxmc_ideal.py
  testsuite/bond_tests.py
  testsuite/create_molecule_position_test.py
  testsuite/read-write-df_test.py
  tutorials/pyMBE_tutorial.ipynb
  tutorials/solution_tutorial.ipynb
Labels: enhancement, ci-improvement, code quality
