Repository pyMBE-dev/pyMBE, pull requests merged in 2025-03, with the labels that each got.

#112 code-cov pmb.setup_lj_interaction
  CHANGELOG.md
  pyMBE.py
  testsuite/delete_entries_in_df.py
  testsuite/lj_tests.py
Labels: enhancement, ci-improvement, code quality

#118 add coverage for `lib.handy_functions`
  CHANGELOG.md
  lib/handy_functions.py
  samples/Beyer2024/globular_protein.py
  samples/Beyer2024/peptide.py
  samples/Beyer2024/weak_polyelectrolyte_dialysis.py
  samples/branched_polyampholyte.py
  samples/peptide_cpH.py
  samples/salt_solution_gcmc.py
  testsuite/CTestTestfile.cmake
  testsuite/test_handy_functions.py
Labels: ci-improvement, code quality

#119 Improve CI testing and pyMBE log
  CHANGELOG.md
  lib/handy_functions.py
  pyMBE.py
  samples/peptide_cpH.py
  testsuite/CTestTestfile.cmake
  testsuite/bond_tests.py
  testsuite/define_and_create_molecules_unit_tests.py
  testsuite/delete_entries_in_df.py
  testsuite/parameter_test.py
  testsuite/seed_test.py
  testsuite/test_handy_functions.py
  testsuite/test_in_out_pmb_df.py
  tutorials/pyMBE_tutorial.ipynb
Labels: ci-improvement, code quality

#120 bugfix: support `backbone_vector` as a list
  CHANGELOG.md
  pyMBE.py
Labels: bug
