Repository pyMBE-dev/pyMBE, pull requests merged in 2025-05, with the labels that each got.

#103 Add a hydrogel builder
  CHANGELOG.md
  README.md
  lib/analysis.py
  lib/handy_functions.py
  lib/lattice.py
  maintainer/standarize_data.py
  parameters/salt/excess_chemical_potential_excess_pressure.csv
  pyMBE.py
  refs/bibliography.bib
  samples/Beyer2024/weak_polyelectrolyte_dialysis.py
  samples/Landsgesell2022/README.md
  samples/Landsgesell2022/plot_P_vs_V.py
  samples/Landsgesell2022/plot_pH_vs_alpha.py
  samples/Landsgesell2022/run_simulations.py
  samples/README.md
  samples/branched_polyampholyte.py
  samples/build_hydrogel.py
  samples/salt_solution_gcmc.py
  samples/weak_polyacid_hydrogel_grxmc.py
  testsuite/CTestTestfile.cmake
  testsuite/data/Landsgesell2022a.csv
  testsuite/data/README.md
  testsuite/data/src/equilibrium_values_gel_MD.csv
  testsuite/data/src/excess_chemical_potential.dat
  testsuite/data/src/weak-gel_total_data.csv
  testsuite/define_and_create_molecules_unit_tests.py
  testsuite/hydrogel_builder.py
  testsuite/hydrogel_tests.py
  testsuite/lattice_builder.py
  testsuite/read-write-df_test.py
Labels: documentation, enhancement

#125 Increase code coverage for various functions
  pyMBE.py
  testsuite/determine_reservoir_concentrations_test_data/data.csv
  testsuite/determine_reservoir_concentrations_unit_test.py
  testsuite/generate_perpendicular_vectors_test.py
  testsuite/henderson_hasselbalch_tests.py
  testsuite/henderson_hasselbalch_tests_data/HH_Donnan_no_pH_list.csv
  testsuite/henderson_hasselbalch_tests_data/HH_no_pH_list.csv
Labels: ci-improvement

#128 cov: get_lj_parameters and read_pmf_df
  pyMBE.py
  testsuite/lj_tests.py
  testsuite/read-write-df_test.py
Labels: ci-improvement

#130 Remove solution_tutorial
  CHANGELOG.md
  figs/branched_polyampholyte.png
  samples/branched_polyampholyte.py
  samples/plot_branched_polyampholyte.py
  tutorials/pyMBE_tutorial.ipynb
  tutorials/solution_tutorial.ipynb
Labels: code quality
